name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show files
        run: ls -la
      - name: Run script
        run: bash hello.sh
      - name: Simulated tests
        run: |
          echo "Running tests"
          exit 1
